/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package natsbook.java.samples;
import io.nats.client.Connection;
import io.nats.client.Nats;
import io.nats.client.impl.NatsMessage;

import java.nio.charset.StandardCharsets;
import java.time.Duration;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void publishNATS() {
        try {
            Connection nc = Nats.connect("nats://localhost:4222"); 

            nc.publish("patient.treatments", "{“tablets”:[panadol, asithromizin]}".getBytes(StandardCharsets.UTF_8)); 
    
            // Make sure the message goes through before we close 
    
            nc.flush(Duration.ZERO); 
    
            nc.close(); 
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public static void main(String[] args) {
        App sampleApp = new App();
        sampleApp.publishNATS();
        System.out.println(sampleApp.getGreeting());
    }
}
