openapi: 3.0.1
info:
  title: PatientData
  description: API Definition of PatientData
  version: 1.0.0
servers:
- url: http://localhost:8290/patient
paths:
  /{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
