server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: publisher
  static_configs:
  - targets:
      - localhost
    labels:
      job: publisher
      __path__: /Users/chanakaf/Documents/source-code/Designing-Microservices-Platforms-with-NATS/chapter8/observability-sample/publisher/publisher.log
- job_name: subscriber
  static_configs:
  - targets:
      - localhost
    labels:
      job: subscriber
      __path__: /Users/chanakaf/Documents/source-code/Designing-Microservices-Platforms-with-NATS/chapter8/observability-sample/subscriber/subscriber.log
- job_name: NATS-4222
  static_configs:
  - targets:
      - localhost
    labels:
      job: nats-4222
      __path__: /Users/chanakaf/Documents/source-code/Designing-Microservices-Platforms-with-NATS/chapter8/observability-sample/nats.log

